function FastClick(a){function b(d,e){return function(){return d.apply(e,arguments)}}var c;this.trackingClick=false;this.trackingClickStart=0;this.targetElement=null;this.lastTouchIdentifier=this.touchStartY=this.touchStartX=0;this.touchBoundary=10;this.layer=a;if(!FastClick.notNeeded(a)){if(deviceIsAndroid){a.addEventListener("mouseover",b(this.onMouse,this),true);a.addEventListener("mousedown",b(this.onMouse,this),true);a.addEventListener("mouseup",b(this.onMouse,this),true)}a.addEventListener("click",
b(this.onClick,this),true);a.addEventListener("touchstart",b(this.onTouchStart,this),false);a.addEventListener("touchmove",b(this.onTouchMove,this),false);a.addEventListener("touchend",b(this.onTouchEnd,this),false);a.addEventListener("touchcancel",b(this.onTouchCancel,this),false);if(!Event.prototype.stopImmediatePropagation){a.removeEventListener=function(d,e,f){var g=Node.prototype.removeEventListener;d==="click"?g.call(a,d,e.hijacked||e,f):g.call(a,d,e,f)};a.addEventListener=function(d,e,f){var g=
Node.prototype.addEventListener;d==="click"?g.call(a,d,e.hijacked||(e.hijacked=function(h){h.propagationStopped||e(h)}),f):g.call(a,d,e,f)}}if(typeof a.onclick==="function"){c=a.onclick;a.addEventListener("click",function(d){c(d)},false);a.onclick=null}}}var deviceIsAndroid=navigator.userAgent.indexOf("Android")>0,deviceIsIOS=/iP(ad|hone|od)/.test(navigator.userAgent),deviceIsIOS4=deviceIsIOS&&/OS 4_\d(_\d)?/.test(navigator.userAgent),deviceIsIOSWithBadTarget=deviceIsIOS&&/OS ([6-9]|\d{2})_\d/.test(navigator.userAgent);
FastClick.prototype.needsClick=function(a){switch(a.nodeName.toLowerCase()){case "button":case "select":case "textarea":if(a.disabled)return true;break;case "input":if(deviceIsIOS&&a.type==="file"||a.disabled)return true;break;case "label":case "video":return true}return/\bneedsclick\b/.test(a.className)};
FastClick.prototype.needsFocus=function(a){switch(a.nodeName.toLowerCase()){case "textarea":return true;case "select":return!deviceIsAndroid;case "input":switch(a.type){case "button":case "checkbox":case "file":case "image":case "radio":case "submit":return false}return!a.disabled&&!a.readOnly;default:return/\bneedsfocus\b/.test(a.className)}};
FastClick.prototype.sendClick=function(a,b){var c,d;document.activeElement&&document.activeElement!==a&&document.activeElement.blur();d=b.changedTouches[0];c=document.createEvent("MouseEvents");c.initMouseEvent(this.determineEventType(a),true,true,window,1,d.screenX,d.screenY,d.clientX,d.clientY,false,false,false,false,0,null);c.forwardedTouchEvent=true;a.dispatchEvent(c)};FastClick.prototype.determineEventType=function(a){if(deviceIsAndroid&&a.tagName.toLowerCase()==="select")return"mousedown";return"click"};
FastClick.prototype.focus=function(a){var b;if(deviceIsIOS&&a.setSelectionRange&&a.type.indexOf("date")!==0&&a.type!=="time"){b=a.value.length;a.setSelectionRange(b,b)}else a.focus()};FastClick.prototype.updateScrollParent=function(a){var b,c;b=a.fastClickScrollParent;if(!b||!b.contains(a)){c=a;do{if(c.scrollHeight>c.offsetHeight){b=c;a.fastClickScrollParent=c;break}c=c.parentElement}while(c)}if(b)b.fastClickLastScrollTop=b.scrollTop};
FastClick.prototype.getTargetElementFromEventTarget=function(a){if(a.nodeType===Node.TEXT_NODE)return a.parentNode;return a};
FastClick.prototype.onTouchStart=function(a){var b,c,d;if(a.targetTouches.length>1)return true;b=this.getTargetElementFromEventTarget(a.target);c=a.targetTouches[0];if(deviceIsIOS){d=window.getSelection();if(d.rangeCount&&!d.isCollapsed)return true;if(!deviceIsIOS4){if(c.identifier===this.lastTouchIdentifier){a.preventDefault();return false}this.lastTouchIdentifier=c.identifier;this.updateScrollParent(b)}}this.trackingClick=true;this.trackingClickStart=a.timeStamp;this.targetElement=b;this.touchStartX=
c.pageX;this.touchStartY=c.pageY;a.timeStamp-this.lastClickTime<200&&a.preventDefault();return true};FastClick.prototype.touchHasMoved=function(a){a=a.changedTouches[0];var b=this.touchBoundary;if(Math.abs(a.pageX-this.touchStartX)>b||Math.abs(a.pageY-this.touchStartY)>b)return true;return false};
FastClick.prototype.onTouchMove=function(a){if(!this.trackingClick)return true;if(this.targetElement!==this.getTargetElementFromEventTarget(a.target)||this.touchHasMoved(a)){this.trackingClick=false;this.targetElement=null}return true};FastClick.prototype.findControl=function(a){if(a.control!==undefined)return a.control;if(a.htmlFor)return document.getElementById(a.htmlFor);return a.querySelector("button, input:not([type=hidden]), keygen, meter, output, progress, select, textarea")};
FastClick.prototype.onTouchEnd=function(a){var b,c,d=this.targetElement;if(!this.trackingClick)return true;if(a.timeStamp-this.lastClickTime<200)return this.cancelNextClick=true;this.cancelNextClick=false;this.lastClickTime=a.timeStamp;b=this.trackingClickStart;this.trackingClick=false;this.trackingClickStart=0;if(deviceIsIOSWithBadTarget){c=a.changedTouches[0];d=document.elementFromPoint(c.pageX-window.pageXOffset,c.pageY-window.pageYOffset)||d;d.fastClickScrollParent=this.targetElement.fastClickScrollParent}c=
d.tagName.toLowerCase();if(c==="label"){if(b=this.findControl(d)){this.focus(d);if(deviceIsAndroid)return false;d=b}}else if(this.needsFocus(d)){if(a.timeStamp-b>100||deviceIsIOS&&window.top!==window&&c==="input"){this.targetElement=null;return false}this.focus(d);this.sendClick(d,a);if(!deviceIsIOS4||c!=="select"){this.targetElement=null;a.preventDefault()}return false}if(deviceIsIOS&&!deviceIsIOS4)if((b=d.fastClickScrollParent)&&b.fastClickLastScrollTop!==b.scrollTop)return true;if(!this.needsClick(d)){a.preventDefault();
this.sendClick(d,a)}return false};FastClick.prototype.onTouchCancel=function(){this.trackingClick=false;this.targetElement=null};FastClick.prototype.onMouse=function(a){if(!this.targetElement)return true;if(a.forwardedTouchEvent)return true;if(!a.cancelable)return true;if(!this.needsClick(this.targetElement)||this.cancelNextClick){if(a.stopImmediatePropagation)a.stopImmediatePropagation();else a.propagationStopped=true;a.stopPropagation();a.preventDefault();return false}return true};
FastClick.prototype.onClick=function(a){if(this.trackingClick){this.targetElement=null;this.trackingClick=false;return true}if(a.target.type==="submit"&&a.detail===0)return true;a=this.onMouse(a);if(!a)this.targetElement=null;return a};
FastClick.prototype.destroy=function(){var a=this.layer;if(deviceIsAndroid){a.removeEventListener("mouseover",this.onMouse,true);a.removeEventListener("mousedown",this.onMouse,true);a.removeEventListener("mouseup",this.onMouse,true)}a.removeEventListener("click",this.onClick,true);a.removeEventListener("touchstart",this.onTouchStart,false);a.removeEventListener("touchmove",this.onTouchMove,false);a.removeEventListener("touchend",this.onTouchEnd,false);a.removeEventListener("touchcancel",this.onTouchCancel,
false)};FastClick.notNeeded=function(a){var b,c;if(typeof window.ontouchstart==="undefined")return true;if(c=+(/Chrome\/([0-9]+)/.exec(navigator.userAgent)||[,0])[1])if(deviceIsAndroid){if(b=document.querySelector("meta[name=viewport]")){if(b.content.indexOf("user-scalable=no")!==-1)return true;if(c>31&&window.innerWidth<=window.screen.width)return true}}else return true;if(a.style.msTouchAction==="none")return true;return false};FastClick.attach=function(a){return new FastClick(a)};
if(typeof define!=="undefined"&&define.amd)define(function(){return FastClick});else if(typeof module!=="undefined"&&module.exports){module.exports=FastClick.attach;module.exports.FastClick=FastClick}else window.FastClick=FastClick;$.fn.serializeObject=function(){var a={};$("input,select,checkbox,password,radio,textarea,input:hidden",this).each(function(){var b=$(this).attr("id"),c=$.trim($(this).val());if(this.type=="checkbox"||this.type=="radio")this.checked||(c="0");a[b]=c});return a};
function htmlEncode(a){return $("<div/>").text(a).html()}function ShowWait(){var a="<br><table cellpadding='0' cellspacing='0' width='100%' >";a+="<tr><td>&nbsp;<tr><td colspan='4' align='center'><img src='Images/progress.gif' alt='progress'>";a+="<tr align='center'><td colspan='4' ><b>Processing request, please wait......";a+="</table>";$("#divWait").html(a);$("#divWait").dialog("open");$("#divWait").dialog("option",{title:"Processing...",position:"center"})}
function EndWait(){$("#divWait").dialog("close")}function SaveInLocalStorage(a,b){if(typeof localStorage!="undefined"){window.localStorage.removeItem("'"+a+"'");window.localStorage.setItem("'"+a+"'",b);return true}else{alert("Your browser does not support local storage, please upgrade to latest browser");return false}}function LoadFromLocalStorage(a,b){var c=window.localStorage.getItem("'"+a+"'");if(c==null)return b==undefined?"":b;return c}
function RemoveFromLocalStorage(a){window.localStorage.removeItem("'"+a+"'")}function ClearLocalStoreage(){if(typeof window.localStorage!="undefined")window.localStorage.clear();else throw"window.localStorage, not defined";}var UserPosition=null;function GetCurrentLocation(a){navigator&&navigator.geolocation?navigator.geolocation.getCurrentPosition(function(b){geo_success(b,a)},geo_error):error("Geolocation is not supported.")}
function geo_success(a,b){UserPosition={Lat:a.coords.latitude,Lng:a.coords.longitude};b!=undefined&&b(UserPosition)}function geo_error(a){if(a.code==1)error("The user denied the request for location information.");else if(a.code==2)error("Your location information is unavailable.");else a.code==3?error("The request to get your location timed out."):error("An unknown error occurred while requesting your location.")}function error(){}
function GetDistance(a,b,c,d){if(c=="0"||d=="0")return 0;if(typeof Number.prototype.toRad==="undefined")Number.prototype.toRad=function(){return this*Math.PI/180};var e=(parseFloat(c)-parseFloat(a)).toRad();b=(parseFloat(d)-parseFloat(b)).toRad();a=parseFloat(a).toRad();c=parseFloat(c).toRad();a=Math.sin(e/2)*Math.sin(e/2)+Math.sin(b/2)*Math.sin(b/2)*Math.cos(a)*Math.cos(c);return 6371*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a))}
function CheckCacheUpdate(){window.applicationCache.addEventListener("updateready",function(){window.applicationCache.swapCache();window.location.reload()})}$.fn.removeHighlight=function(){return this.find(".highlight").each(function(){with(this.parentNode){replaceChild(this.firstChild,this);normalize()}}).end()};
$.fn.highlighttext=function(a){if(a!=""){var b=function(c,d){var e=0;if(c.nodeType==3){var f=c.data.toUpperCase().indexOf(d);if(f>=0){e=document.createElement("span");e.className="highlight";f=c.splitText(f);f.splitText(d.length);var g=f.cloneNode(true);e.appendChild(g);f.parentNode.replaceChild(e,f);e=1}}else if(c.nodeType==1&&c.childNodes&&!/(script|style)/i.test(c.tagName))for(f=0;f<c.childNodes.length;++f)f+=b(c.childNodes[f],d);return e};return this.each(function(){b(this,a.toUpperCase())})}};
var stl=[];stl[0]={id:4405,n:"Adarsh Nagar",l:1};stl[1]={id:42,n:"AIIMS",l:1};stl[2]={id:90,n:"Akshardham",l:2};stl[3]={id:104,n:"Anand Vihar",l:2};stl[4]={id:51,n:"Arjan Garh",l:1};stl[5]={id:108,n:"Ashok Park Main",l:3};stl[6]={id:24,n:"Azadpur",l:1};stl[7]={id:135,n:"Badarpur",l:4};stl[8]={id:85,n:"Barakhamba",l:2};stl[9]={id:97,n:"Botanical Garden",l:2};stl[10]={id:37,n:"Central Secretariat",l:1};stl[11]={id:31,n:"Chandni Chowk",l:1};stl[12]={id:32,n:"Chawri Bazar",l:1};
stl[13]={id:48,n:"Chhattarpur",l:1};stl[14]={id:29,n:"Civil Lines",l:1};stl[15]={id:138,n:"Delhi Aero City",l:5};stl[16]={id:137,n:"Dhaula Kuan",l:5};stl[17]={id:1,n:"Dilshad Garden",l:6};stl[18]={id:66,n:"Dwaraka Mor",l:2};stl[19]={id:65,n:"Dwarka",l:2};stl[20]={id:4408,n:"Dwarka Sec-21-Airport",l:5};stl[21]={id:60,n:"Dwarka Sector - 10",l:2};stl[22]={id:61,n:"Dwarka Sector - 11",l:2};stl[23]={id:62,n:"Dwarka Sector - 12",l:2};stl[24]={id:63,n:"Dwarka Sector - 13",l:2};
stl[25]={id:64,n:"Dwarka Sector - 14",l:2};stl[26]={id:57,n:"Dwarka Sector - 21",l:2};stl[27]={id:58,n:"Dwarka Sector - 8",l:2};stl[28]={id:59,n:"Dwarka Sector - 9",l:2};stl[29]={id:50,n:"Ghotorni",l:1};stl[30]={id:98,n:"Golf Course",l:2};stl[31]={id:129,n:"Govindpuri",l:4};stl[32]={id:43,n:"Green Park",l:1};stl[33]={id:26,n:"Gtb Nagar",l:1};stl[34]={id:52,n:"Gurudronacharya",l:1};stl[35]={id:44,n:"Hauz Khas",l:1};stl[36]={id:56,n:"Huda City Centre",l:1};stl[37]={id:139,n:"I.G.I Airport",l:5};
stl[38]={id:55,n:"IFFCO Chowk",l:1};stl[39]={id:41,n:"INA",l:1};stl[40]={id:4229,n:"Inder Lok",l:3};stl[41]={id:88,n:"Indraprastha",l:2};stl[42]={id:22,n:"Jahangirpuri",l:1};stl[43]={id:71,n:"Janak Puri East",l:2};stl[44]={id:70,n:"Janak Puri West",l:2};stl[45]={id:123,n:"Jangpura",l:4};stl[46]={id:131,n:"Jasola",l:4};stl[47]={id:122,n:"Jawaharlal Nehru Stadium",l:4};stl[48]={id:83,n:"Jhandewalan",l:2};stl[49]={id:2,n:"Jhil mil",l:6};stl[50]={id:40,n:"Jorbagh",l:1};
stl[51]={id:126,n:"Kailash Colony",l:4};stl[52]={id:128,n:"Kalkaji Mandir",l:4};stl[53]={id:14,n:"Kanhaiya Nagar",l:6};stl[54]={id:103,n:"Karkar Duma",l:2};stl[55]={id:82,n:"Karol Bagh",l:2};stl[56]={id:8,n:"Kashmere Gate",l:6};stl[57]={id:105,n:"Kaushambi",l:2};stl[58]={id:15,n:"Keshav Puram",l:6};stl[59]={id:121,n:"Khan Market",l:4};stl[60]={id:78,n:"Kirti Nagar",l:2};stl[61]={id:17,n:"Kohat Enclave",l:6};stl[62]={id:124,n:"Lajpat Nagar",l:4};stl[63]={id:100,n:"Laxmi Nagar",l:2};
stl[64]={id:111,n:"Madi Pur",l:3};stl[65]={id:45,n:"Malviya Nagar",l:1};stl[66]={id:86,n:"Mandi House",l:2};stl[67]={id:3,n:"Mansrover park",l:6};stl[68]={id:91,n:"Mayur Vihar-I",l:2};stl[69]={id:92,n:"Mayur Vihar-I Ext",l:2};stl[70]={id:54,n:"MG Road",l:1};stl[71]={id:25,n:"Model Town",l:1};stl[72]={id:133,n:"Mohan Cooperative",l:4};stl[73]={id:125,n:"Moolchand",l:4};stl[74]={id:77,n:"Moti Nagar",l:2};stl[75]={id:120,n:"Mundka",l:3};stl[76]={id:117,n:"Nangloai",l:3};
stl[77]={id:118,n:"Nangloai Rly. Station",l:3};stl[78]={id:67,n:"Nawada",l:2};stl[79]={id:127,n:"Nehru Place",l:4};stl[80]={id:16,n:"Netaji Subash Place",l:6};stl[81]={id:93,n:"New Ashok Nagar",l:2};stl[82]={id:33,n:"New Delhi",l:1};stl[83]={id:4225,n:"New Delhi-Airport Express",l:5};stl[84]={id:101,n:"Nirman Vihar",l:2};stl[85]={id:99,n:"Noida City Center",l:2};stl[86]={id:94,n:"Noida Sect 15",l:2};stl[87]={id:95,n:"Noida Sect 16",l:2};stl[88]={id:96,n:"Noida Sect 18",l:2};
stl[89]={id:130,n:"Okhla",l:4};stl[90]={id:112,n:"Paschim Vihar (East)",l:3};stl[91]={id:113,n:"Paschim Vihar (West)",l:3};stl[92]={id:36,n:"Patel Chowk",l:1};stl[93]={id:80,n:"Patel Nagar",l:2};stl[94]={id:114,n:"Peera Garhi",l:3};stl[95]={id:18,n:"Pitam Pura",l:6};stl[96]={id:87,n:"Pragati Maidan",l:2};stl[97]={id:11,n:"Pratap Nagar",l:6};stl[98]={id:102,n:"Preet Vihar",l:2};stl[99]={id:10,n:"Pul Bangash",l:6};stl[100]={id:109,n:"Punjabi Bagh",l:3};stl[101]={id:47,n:"Qutab Minar",l:1};
stl[102]={id:84,n:"R K Ashram Marg",l:2};stl[103]={id:39,n:"Race Course",l:1};stl[104]={id:119,n:"Rajdhani Park",l:3};stl[105]={id:81,n:"Rajendra Place",l:2};stl[106]={id:35,n:"Rajiv Chowk",l:1};stl[107]={id:75,n:"Rajouri Garden",l:2};stl[108]={id:76,n:"Ramesh Nagar",l:2};stl[109]={id:21,n:"Rithala",l:6};stl[110]={id:20,n:"Rohini West",l:6};stl[111]={id:19,n:"RohiniEast",l:6};stl[112]={id:46,n:"Saket",l:1};stl[113]={id:132,n:"Sarita Vihar",l:4};stl[114]={id:4230,n:"Satguru Ram Singh Marg",l:7};
stl[115]={id:6,n:"Seelam Pur",l:6};stl[116]={id:79,n:"Shadi Pur",l:2};stl[117]={id:4,n:"Shahdara",l:6};stl[118]={id:12,n:"Shastri Nagar",l:6};stl[119]={id:7,n:"Shastri Park",l:6};stl[120]={id:110,n:"Shivaji Park",l:3};stl[121]={id:136,n:"Shivaji Stadium",l:5};stl[122]={id:53,n:"Sikanderpur",l:1};stl[123]={id:73,n:"Subash Nagar",l:2};stl[124]={id:49,n:"Sultanpur",l:1};stl[125]={id:116,n:"Surajmal Stadium",l:3};stl[126]={id:74,n:"Tagore Garden",l:2};stl[127]={id:72,n:"Tilak Nagar",l:2};
stl[128]={id:9,n:"Tis Hazari",l:6};stl[129]={id:134,n:"Tughlakabad",l:4};stl[130]={id:38,n:"Udyog Bhawan",l:1};stl[131]={id:115,n:"Udyog Nagar",l:3};stl[132]={id:69,n:"Uttam Nagar East",l:2};stl[133]={id:68,n:"Uttam Nagar West",l:2};stl[134]={id:106,n:"Vaishali",l:2};stl[135]={id:28,n:"Vidhan Sabha",l:1};stl[136]={id:27,n:"Viswavidyalaya",l:1};stl[137]={id:5,n:"Welcome",l:6};stl[138]={id:89,n:"Yamuna Bank",l:2};
var HistoryList=[],_msg=null,map,LinesInfo=["","Yellow Line","Blue Line","Green Line-Indrlok to Mundka","Violet Line","Airport Express","Red Line","Green Line"],CMD_HOME=0,CMD_SEARCH=1,CMD_SEARCH_ROUTE=2,CMD_SEARCHROUTE=3,CMD_HISTORY=4,CMD_SHOW_STATION_INFO=5,CMD_SHOW_ON_MAP=6,CMD_AUTOCOMPLETE=7,CMD_ALERT=8,CMD_LINEINFO=9,M=new Mobile;function Mobile(){this.StationID=this.ToID=this.FromID=this.CurrentCommand=0;this.ReqFor="route";this.Line=0;this.SelectStationFor="from"}Mobile.prototype.Save=function(){SaveInLS(this)};
Mobile.prototype.Load=function(){LoadFromLS(this)};function GetStation(a){for(var b=0;b<stl.length;b++)if(stl[b].id==a)return stl[b];return{n:"",l:""}}function SaveInLS(a){for(var b in a)if(a[b]!=null)(typeof a[b]).toString()!="function"&&SaveInLocalStorage(b,JSON.stringify(a[b]));else RemoveFromLocalStorage(b)}
function LoadFromLS(a){for(var b in a){var c=LoadFromLocalStorage(b);if(c!="undefined"&&c!="null"&&c!=null&&c!=undefined)if((typeof a[b]).toString()!="function")a[b]=c==""?c:JSON.parse(c)}}
function RunCommand(a){if(a){M.CurrentCommand=a;M.Save()}switch(M.CurrentCommand){case CMD_HOME:$.mobile.changePage("#divHome");break;case CMD_SEARCH_ROUTE:$.mobile.changePage("#divSearchPage");break;case CMD_SEARCHROUTE:$.mobile.changePage("#divRouteListPage");break;case CMD_HISTORY:$.mobile.changePage("#divFavouriteListPage");break;case CMD_SHOW_STATION_INFO:$.mobile.changePage("#divStationInfoPage");break;case CMD_AUTOCOMPLETE:$.mobile.changePage("#divAutoCompletePage");break;case CMD_ALERT:$.mobile.changePage("#divAlertPage");
break;case CMD_LINEINFO:$.mobile.changePage("#divLineInfoPage")}return false}
$(document).bind("pagechange",function(a,b){M.Load();var c=b.toPage.attr("id");console.log("pagechange-"+c+"-"+M.CurrentCommand);switch(c){case "divSearchPage":FillStations();break;case "divFavouriteListPage":ShowHistory();break;case "divRouteListPage":switch(M.ReqFor){case "route":GetRoute();break;case "fare":GetFare();break;case "station":RunCommand(CMD_SHOW_STATION_INFO)}break;case "divStationInfoPage":GetStationInfo();break;case "divAutoCompletePage":FillAutoComplete();break;case "divAlertPage":ShowAlert();
break;case "divLineInfoPage":ShowLineInfo()}});$(document).bind("pageinit",function(){FastClick.attach(document.body);$.mobile.defaultPageTransition="none";CheckCacheUpdate()});function GetData(a,b){$.ajax({url:Root+a,success:b})}
function SearchNow(){M.Load();var a="";switch(M.ReqFor){case "route":case "fare":if(M.FromID==""||M.ToID=="")a="Please enter source and destination correctly";else if(M.FromID==M.ToID)a="Source and Destination cannot be same, Please select different stations";break;case "station":if(M.FromID=="")a="Please select station to display";break;case "line":if(M.FromID=="")a="Please metro line to display"}a!=""?ShowMessage(a):RunCommand(CMD_SEARCHROUTE)}
function SearchFor(a){switch(a){case "route":$("#btnSearch").text("Get Route");break;case "fare":$("#btnSearch").text("Get Fare");break;case "station":$("#btnSearch").text("Get Station Info")}$("#divSearch").trigger("refresh");M.ReqFor=a;M.Save();RunCommand(CMD_SEARCH_ROUTE)}
function FillStations(){M.Load();NoData(M.FromID)||$("#btnAddFrom").text("From : "+GetStation(M.FromID).n);NoData(M.ToID)||$("#btnAddTo").text("To : "+GetStation(M.ToID).n);$("#trTo").hide();M.ReqFor!="station"?$("#trTo").show():$("#btnAddFrom").text("Station : "+GetStation(M.FromID).n);$("#divSearch").trigger("create")}
function GetFare(){AddPageTitle("Find Fare");$("#divRouteList").html("");ShowProcessingMessage();History=JSON.parse(LoadFromLocalStorage("History","[]"));var a=GetFromHistory("fare",M.FromID,M.ToID);if(a==-1){a=GetFromHistoryList("fare",M.FromID,M.ToID);a==-1?GetData("query.ashx?Action=GetFare&Data1="+M.FromID+"&Data2="+M.ToID,function(b){ShowFare(RemoveSomeeText(b))}):ShowFare(HistoryList[a].Data)}else ShowFare(History[a].Data)}function AddPageTitle(a){$(".lblHeader").text(a)}
function ShowFare(a){HideProcessingMessage();var b=JSON.parse(a);AddPageTitle("Fare");var c=[""];c[c.length]="<ul data-role='listview' data-inset='true'><li><a href='#'><h2>"+GetStation(b.FromID).n+" - "+GetStation(b.ToID).n+"</h2><p>Fare : "+b.Fare+"</p></a>";indx=GetFromHistory("fare",b.FromID,b.ToID);c[c.length]="</li> </ul>";c[c.length]=indx==-1||History[indx].Status==1?"<a data-role='button' href='#' data-icon='plus' data-theme='a' id='aAddToFav'>Add to My List</a>":"<a data-role='button' href='#' data-icon='minus' data-theme='c' id='aAddToFav'>Remove from My List</a>";
$("#divRouteList").html(c.join(""));AddToHistoryList("fare",b.FromID,b.ToID,a);$("#divRouteList #aAddToFav").click(function(){if(indx==-1){AddToFavourites("fare",b.FromID,b.ToID,a);_msg={msg:"Added to favorite list. You can view it later in 'My List'.",header:"Added"}}else{RemoveFavourite(indx,0);_msg={msg:"Removed from favorite list",header:"Removed"}}RunCommand(CMD_ALERT)});$("#divRouteList").trigger("create");indx!=-1&&History[indx].Status==1&&RemoveFavourite(indx,1)}
function GetRoute(){M.Load();if(M.FromID==""||M.ToID=="")ShowMessage("Please select source and destination station correctly");else if(M.FromID==M.ToID)ShowMessage("Source and Destination cannot be same, Please select different stations");else{ShowProcessingMessage();$("#divRouteList").html("");History=JSON.parse(LoadFromLocalStorage("History","[]"));var a=GetFromHistory("route",M.FromID,M.ToID);if(a==-1){a=GetFromHistoryList("route",M.FromID,M.ToID);a==-1?GetData("query.ashx?Action=GetRoute&Data1="+
M.FromID+"&Data2="+M.ToID,function(b){ShowRoute(RemoveSomeeText(b))}):ShowRoute(HistoryList[a].Data)}else ShowRoute(History[a].Data)}}
function ShowRoute(a){HideProcessingMessage();AddPageTitle("Route");var b=[""];if(a==""){b[b.length]="<ul data-role='listview' data-inset='true' data-theme='c' data-dividertheme='f'><li data-theme='b'>Route</li>";b[b.length]="<li data-theme='a' class='interchange' data-icon='info' ><a href='#'><h3>No route found, please try later</h3></a></li>";b[b.length]="</ul>";$("#divRouteList").html(b.join(""));$("#divRouteList").trigger("create")}else{var c=JSON.parse(a);b[b.length]="<ul data-role='listview' data-inset='true'><li><a href='#' ><h2>"+
GetStation(c.FromID).n+" - "+GetStation(c.ToID).n+"</h2><p><b>"+c.Distance+"</b> Km in <b>"+c.Time+" m</b>, <b>Fare : "+c.Fare+"</b></p></a></li></ul>";b[b.length]="<div class='infobox'>Click on station name to see more info.</div>";var d=c.RouteInfo.split("-");b[b.length]="<ul data-role='listview' data-inset='true' data-theme='c' data-dividertheme='b'><li data-theme='b'>Route</li>";$(d).each(function(e){if(this!=""){var f=this.split("^"),g=GetStation(f[0]);if(g.n==""&&g.l==""){if(e>0){e=d[e-1].split("^");
e=GetStation(e[0]);b[b.length]="<li data-theme='b' class='interchange' data-icon='info' ><a href='#'><h3>Interchange at "+e.n+"</h3></a></li>"}}else{b[b.length]="<li data-icon='info'><a href='#' class='st' data-id='"+f[0]+"'>";b[b.length]="<h3><span class='ui-icon ui-icon-checkbox-off ui-icon-shadow lsymb line_"+g.l+"' >&nbsp;&nbsp;&nbsp;&nbsp;</span>"+g.n+"</h3>";b[b.length]="<p class='ui-li-aside'><strong>"+(f[1]!=""?f[1]+" (Rs)":"")+"<br/>"+(f[2]!=""?f[2]+" (Km)":"")+"</strong></p>"}}});b[b.length]=
"</ul>";indx=GetFromHistory("route",c.FromID,c.ToID);b[b.length]=indx==-1||History[indx].Status==1?"<a data-corners='false' data-role='button' href='#' data-icon='plus' data-theme='b' id='aAddToFav'>Add to My List</a>":"<a data-corners='false' data-role='button' href='#' data-icon='minus' data-theme='c' id='aAddToFav'>Remove from My List</a>";$("#divRouteList").html(b.join(""));AddToHistoryList("route",c.FromID,c.ToID,a);$("#divRouteList .st").bind("click",function(){var e=$(this).data("id");M.FromID=
e;M.Save();RunCommand(CMD_SHOW_STATION_INFO)});$("#divRouteList #aAddToFav").click(function(){if(indx==-1){AddToFavourites("route",c.FromID,c.ToID,a);_msg={msg:"Added to favorite list. You can view it later in 'My List'.",header:"Added"}}else{RemoveFavourite(indx,0);_msg={msg:"Removed from favorite list",header:"Removed"}}RunCommand(CMD_ALERT)});$("#divRouteList").trigger("create");indx!=-1&&History[indx].Status==1&&RemoveFavourite(indx,1)}}$(document).ready(function(){});History=[];
function ShowHistory(){History=JSON.parse(LoadFromLocalStorage("History","[]"));var a=["<ul data-role='listview' data-inset='true' data-theme='c' data-dividertheme='f'>"];if(History.length==0){a[a.length]="<li data-role='list-divider' data-theme='b'>No record in history</li><li><p>Add routes, fare and stations to your history</p></li></ul>";$("#divFavouriteList").html(a.join(""))}else{var b=["<li data-role='list-divider' data-theme='b'>Routes Searched<span class='ui-li-count' id='rtctr'></span></li>"],
c=["<li data-role='list-divider' data-theme='b'>Fares Searched<span class='ui-li-count' id='frctr'></span></li>"],d=["<li data-role='list-divider' data-theme='b'>Station Searched<span class='ui-li-count' id='stctr'></span></li>"],e=0,f=0,g=0;$(History).each(function(h){var i=JSON.parse(this.Data);switch(this.Type){case "route":++e;b[b.length]="<li><a href='#' class='al' data-class='route'  data-index='"+h+"'>";b[b.length]="<h2>"+GetStation(this.FromID).n+" - "+GetStation(this.ToID).n+"</h2>";b[b.length]=
"<p>"+i.Distance+" KM in "+i.Time+" m - Rs. "+i.Fare+"</p></a>";b[b.length]="<a href='#' data-icon='delete' onclick='RemoveFavourite("+h+",1)'></a></li>";break;case "fare":++f;c[c.length]="<li><a href='#' class='al' data-class='fare'  data-index='"+h+"'>";c[c.length]="<h2>"+GetStation(this.FromID).n+" - "+GetStation(this.ToID).n+"</h2>";c[c.length]="<p>Rs. "+i.Fare+"</p></a>";c[c.length]="<a href='#' data-icon='delete' onclick='RemoveFavourite("+h+",1)'></a></li>";break;case "station":++g;d[d.length]=
"<li><a href='#' class='al' data-class='station'  data-index='"+h+"'>";d[d.length]="<h2>"+GetStation(this.FromID).n+"</h2>";d[d.length]="<p>Phone : "+i.Phone+", Mobile : "+i.Mobile+"</p></a>";d[d.length]="<a href='#' data-icon='delete' onclick='RemoveFavourite("+h+",1)'></a></li>"}});if(f>0)b[b.length]=c.join("");if(g>0)b[b.length]=d.join("");b[b.length]="</ul>";a[a.length]=b.join("");$("#divFavouriteList").html(a.join(""));$("#rtctr").text(e);$("#frctr").text(f);$("#stctr").text(g);$("#divFavouriteList a.al").bind("click",
function(){var h=$(this).data("index");M.FromID=History[h].FromID;M.ToID=History[h].ToID;M.ReqFor=$(this).data("class");M.Save();RunCommand(CMD_SEARCHROUTE)})}$("#divFavouriteList").trigger("create")}function RemoveFavourite(a,b){if(History[a]!=undefined){if(b==0)History[a].Status=1;else History.splice(a,1);SaveInLocalStorage("History",JSON.stringify(History))}M.CurrentCommand==CMD_HISTORY&&RunCommand(CMD_HISTORY)}
function AddToFavourites(a,b,c,d){if(GetFromHistory(a,b,c)==-1){History[History.length]={Type:a,FromID:b,ToID:c,Data:d,Status:0};SaveInLocalStorage("History",JSON.stringify(History));History=JSON.parse(LoadFromLocalStorage("History","[]"))}}
function AddToHistoryList(a,b,c,d){if(GetFromHistoryList(a,b,c)==-1){HistoryList.length==10&&HistoryList.splice(1,9);HistoryList[HistoryList.length]={Type:a,FromID:b,ToID:c,Data:d,Status:0};SaveInLocalStorage("HistoryList",JSON.stringify(HistoryList));HistoryList=JSON.parse(LoadFromLocalStorage("HistoryList","[]"))}}
function GetFromHistoryList(a,b,c){for(var d=0;d<HistoryList.length;d++)switch(M.ReqFor){case "line":case "station":if(HistoryList[d].Type==a&&HistoryList[d].FromID==b)return d;break;default:if(HistoryList[d].Type==a&&HistoryList[d].FromID==b&&HistoryList[d].ToID==c)return d}return-1}
function GetFromHistory(a,b,c){for(var d=0;d<History.length;d++)switch(M.ReqFor){case "line":case "station":if(History[d].Type==a&&History[d].FromID==b)return d;break;default:if(History[d].Type==a&&History[d].FromID==b&&History[d].ToID==c)return d}return-1}
function GetStationInfo(){ShowProcessingMessage();M.Load();History=JSON.parse(LoadFromLocalStorage("History","[]"));var a=GetFromHistory("station",M.FromID,-1);if(a==-1){a=GetFromHistoryList("station",M.FromID,-1);a==-1?GetData("query.ashx?Action=GetStationInfo&Data1="+M.FromID,function(b){ShowStationInfo(RemoveSomeeText(b))}):ShowStationInfo(HistoryList[a].Data)}else ShowStationInfo(History[a].Data)}
function ShowStationInfo(a){HideProcessingMessage();AddPageTitle("Station Info");var b=["<ul data-role='listview' data-inset='true' data-theme='c' data-dividertheme='f'>"];b[b.length]="<li data-role='list-divider' data-theme='b'>Station Info</li>";if(NoData(a)){b[b.length]="<li><a href='#' >";b[b.length]="<h2>No Information found for this station</h2>";b[b.length]="<p>Please try later.</p></a>"}var c=JSON.parse(a);b[b.length]="<li><a href='#' onclick='ShowPopUpOption()'>";b[b.length]="<h2>"+c.StationName+
"</h2>";b[b.length]="<p>"+(c.Phone!=""?"<b>Phone : </b>"+c.Phone:"")+"</br>";b[b.length]=c.Mobile!=""?"<b>Mobile : </b>"+c.Mobile:"";b[b.length]="</p></a></li>";b[b.length]="<li  style='background-color:white'>";var d=GetStation(c.ID);NoData(c.Line)||(b[b.length]="<a href='#' data-role='button' data-mini='true' data-inline='true' data-icon='info' class='line_"+d.l+"' onclick='GetLineInfo("+d.l+")'>"+LinesInfo[d.l]+"</a>");NoData(c.Opening)||(b[b.length]="<a href='#' data-role='button' data-mini='true' data-inline='true' data-icon='check' data-theme='c' class='infobox'><b>Opened : </b>"+
c.Opening+"</a>");NoData(c.Layout)||(b[b.length]="<a href='#' data-role='button' data-mini='true' data-inline='true' data-icon='check' data-theme='c' class='infobox'><b>Layout : </b>"+c.Layout+"</a>");NoData(c.Connections)||(b[b.length]="<a href='#' data-role='button' data-mini='true' data-inline='true' data-icon='check' data-theme='c' class='infobox'><b>Connections : </b>"+c.Connections+"</a>");b[b.length]="</li>";b[b.length]="</ul>";indx=GetFromHistory("station",c.ID,-1);b[b.length]=indx==-1||History[indx].Status==
1?"<a data-role='button' href='#' data-icon='plus' data-theme='a' id='aAddToFav'>Add to My List</a>":"<a data-role='button' href='#' data-icon='minus' data-theme='c' id='aAddToFav'>Remove from My List</a>";$("#divStationInfo").html(b.join(""));AddToHistoryList("station",c.ID,-1,a);$("#divStationInfo a.aMap").bind("click",function(){ShowStationOnMap(c)});$("#divStationInfo #aAddToFav").click(function(){if(indx==-1){AddToFavourites("station",c.ID,-1,a);_msg={msg:"Added to favorite list. You can view it later in 'My List'.",
header:"Added"}}else{RemoveFavourite(indx,0);_msg={msg:"Removed from favorite list",header:"Removed"}}RunCommand(CMD_ALERT)});$("#divStationInfo").trigger("create");indx!=-1&&History[indx].Status==1&&RemoveFavourite(indx,1)}var autocompleteFor;function AutoComplete(a){M.SelectStationFor=a;M.Save();RunCommand(CMD_AUTOCOMPLETE)}
function FillAutoComplete(){var a=["<table class='alphalist' style='width:100% !important'><tr><td>"];a[a.length]="<input type='search' name='password' id='txtSearchStation' value='' placeholder='type station name'>";a[a.length]="</td></tr>";a[a.length]="<tr><td><div id='divFilteredList'></div></td></tr>";a[a.length]="</table>";$("#divAlphabets").html(a.join(""));$("#divAlphabets").trigger("create");$("#txtSearchStation").focus();FilterStation("a");$("#divAlphabets #txtSearchStation").keyup(function(){FilterStation($("#txtSearchStation").val())})}
String.prototype.startsWith=function(a){return this.substr(0,a.length)==a};
function FilterStation(a){var b=["<ul data-role='listview' data-inset='true' data-theme='b'  data-dividertheme='f'>"],c=[];$(stl).each(function(){if(this.n.toString().toLowerCase().startsWith(a.toLowerCase())){b[b.length]="<li><a href='#' class='aSelectStation' data-index='"+this.id+"'>"+GetStation(this.id).n+"</a></li>";c.push(this.n)}});for(var d=0,e=0;e<stl.length;e++){if(stl[e].n.toLowerCase().indexOf(a.toLowerCase())>-1&&$.inArray(stl[e].n,c)==-1||a==""){c.push(stl[e].n);b[b.length]="<li ><a href='#' class='aSelectStation' data-index='"+
stl[e].id+"'>"+GetStation(stl[e].id).n+"</a></li>";d++}if(d==10)break}b[b.length]="</ul>";$("#divFilteredList").html(b.join(""));$("#divFilteredList").trigger("create");$("#divFilteredList a.aSelectStation").bind("click",function(){var f=$(this).data("index");if(M.SelectStationFor=="from")M.FromID=f;else M.ToID=f;M.Save();RunCommand(CMD_SEARCH_ROUTE)})}function NoData(a){if(a==undefined)return true;if(a.length==0)return true}
function BindLabel(){$("select[data-label]").each(function(){UpdateLabel(this)});$("select[data-label]").bind("change",function(){UpdateLabel(this)})}function UpdateLabel(a){var b=$(a).data("label");$("option",a).each(function(){$(this).text($(this).text().replace(b,""))});var c=$("option:selected",a).text();$("option:selected",a).text(b+c);try{$(a).selectmenu("refresh")}catch(d){}}
function ShowProcessingMessage(){$.mobile.loading("show",{text:"Loading..",textVisible:true,theme:"a",textonly:false,html:""})}function HideProcessingMessage(){$.mobile.loading("hide")}var _alerttimer=null;function ShowAlert(){$("#divAlertPage").trigger("create");_alerttimer!=null&&window.clearTimeout(_alerttimer);if(_msg!=null){$(".lblHeader").text(_msg.header);$("#divMsg").html(_msg.msg)}_alerttimer=window.setTimeout(function(){$(".ui-dialog").dialog("close")},3E3)}
function RemoveSomeeText(a){var b=a.indexOf("<!--SCRIPT GENERATED BY SERVER! PLEASE REMOVE--\>");if(b!=-1)a=a.substr(0,b);return a}
function CreateFooter(){var a="";switch(M.CurrentCommand){case CMD_SEARCHROUTE:switch(M.ReqFor){case "route":case "fare":a="divFooterSearchResult";break;case "station":a="divFooterStationInfo"}break;case CMD_SHOW_STATION_INFO:a="divFooterStationInfo";break;case CMD_HISTORY:a="divFooterFavouriteList"}if(a!=""){var b=["<div data-role='footer' style='border: 1px solid #86D641; background: #6ABA2F; color: #fff; text-shadow: 0 1px 1px #335413; font-weight: bold;' class='footerbar' data-position='fixed' data-fullscreen='true'><fieldset class='ui-grid-b'><div class='ui-block-a'><a href='#' style='border-radius:0px;' data-role='button' data-mini='true'  data-icon='bars' data-theme='a' onclick='RunCommand(CMD_HISTORY)'>My List</a></div>"];if(a==
"divFooterStationInfo")b[b.length]="<div class='ui-block-b'><a href='#"+a+"Panel' style='border-radius:0px;' data-role='button' data-mini='true' data-icon='gear' data-theme='a' >Options</a></div>";b[b.length]="</fieldset></div>";$("#"+a).html(b.join(""));$("#"+a).trigger("create");$(".footerbar").trigger("create")}}function GetLineInfo(a){M.Line=a;M.Save();RunCommand(CMD_LINEINFO)}
function ShowLineInfo(){History=JSON.parse(LoadFromLocalStorage("History","[]"));var a=GetFromHistory("line",M.Line,-1);if(a==-1){a=GetFromHistoryList("line",M.Line,-1);a==-1?GetData("query.ashx?Action=GetLineInfo&Data1="+M.Line,function(b){DisplayLineInfo(RemoveSomeeText(b))}):DisplayLineInfo(HistoryList[a].Data)}else DisplayLineInfo(History[a].Data)}
function DisplayLineInfo(a){var b=JSON.parse(a);$("#li_LineName").text(b.Name);var c=["<ul data-role='listview' data-inset='true' data-theme='b'><li data-role='list-divider'>"+b.Name+"<span class='ui-li-count' style='background-color: "+b.Color+"'></span></li><li data-icon='false'><a href='#'><p>"+b.Description+"</p><p>From "+GetStation(b.FirstStation).n+" To "+GetStation(b.LastStation).n+"</p><br />"];c[c.length]="<p><strong>Opened on </strong>"+b.Opening+"</p>";c[c.length]="<p><strong>Status </strong>"+
b.Status+"</p>";c[c.length]="</a></li>";c[c.length]="<ul data-role='listview' data-inset='true' data-theme='b'><li data-role='list-divider'>Route<span class='ui-li-count'><strong>"+b.Stations+"</strong> Stations, <strong>"+b.Length+"</strong> Km</span></li>";c[c.length]="<li data-icon='false'><a href='/Images/Line/map_"+b.ID+".jpg' target='_blank'><p><img src='/Images/Line/map_"+b.ID+".jpg' style='width: 100%; height: 200px' /></p><p class='ui-li-aside'></p></a></li>";c[c.length]="<ul data-role='listview' data-inset='true' data-theme='b'><li data-role='list-divider'>Image</li><li data-icon='false'><a href='/Images/Line/"+
b.ID+".jpg' target='_blank'><p><img src='/Images/Line/"+b.ID+".jpg' style='width: 100%; height: 200px' /></p></a></li>";c[c.length]="</ul>";$("#divLineInfo").html(c.join(""));$("#divLineInfo").trigger("create");AddToHistoryList("line",b.ID,-1,a)}
function ShowMessage(a){var b=["<ul data-role='listview' data-icon='false' data-inset='true' style='min-width: 210px; background-color:red'  data-theme='b'>"];b[b.length]="<li><a  class='err' href='#'>"+a+"</a></li>";b[b.length]="</ul>";$("#popupContent").html(b.join(""));$("#popupContent").trigger("create");$("#popupMenu").popup();$("#popupMenu").popup("open")}
function ShowPopUpOption(a){var b=[""];if(a!=undefined)b[b.length]=a;else{b[b.length]="<ul data-role='listview' data-inset='true' style='min-width: 210px;' data-theme='a'>";switch(M.CurrentCommand){case CMD_SHOW_STATION_INFO:b[b.length]="<li><a href='#'>View Station Info</a></li>";b[b.length]="<li><a href='#'>View Line Info</a></li>"}b[b.length]="</ul>"}$("#popupContent").html(b.join(""));$("#popupContent").trigger("create");$("#popupMenu").popup();$("#popupMenu").popup("open")};
